Portfolio: details popup window
shm04/portfolio pull request #8
Opened 2023-04-12 17:54 UTC by shm04

## Details popup window
### In this pull request I add the following changes: 

- When the user clicks (or taps) the button to check project details, the popup with details about the project appears. ✔️ 
- When the user clicks (or taps) the close (X) button, the popup disappears. ✔️ 
- Mobile popup. ✔️ 
- Desktop popup. ✔️

2023-04-12 21:19 UTC, Zuhaib042 requested changes
Hi @shm04 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/3o7qDQAFlF8mZjv6fK/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-12 21:19 UTC, Zuhaib042 commented on index.html
> +            <div class="card 1">
- [ ] Two of the main requirements of this milestone are: 
1) to create all the projects cards dynamically 
2) Then, to build popups for each card dynamically also.
To fulfill these both requirements, we make use of the information we stored in the array of objects in JS file. Right now, you are creating popups dynamically from that array but you are not creating the projects cards dynamically so please consider removing everything inside the `<section class="work" id="work">` and create all the cards dynamically from the same array of objects.
This way adding projects in the future will be easy, all you need to do would be to add another object in that array.
-  You need to update the main page so that the projects section is created dynamically using the information stored in that JavaScript object. Remember, all of the HTML in that section is created when the page loads.
- After that, you could implement the popup window.

2023-04-12 21:19 UTC, Zuhaib042 commented on script.js
> +          <a href="${project.source}">See source<img src="/imgs-p/github-white.png"></a>
- [ ] These two images links are broken. kindly consider fixing them by adding a `.` in the src link like this: `./imgs-p/see-live-icon.png`

2023-04-12 21:19 UTC, Zuhaib042 commented on script.js
> +      <div class="buttons one">
- [ ] Your project popup looks fine in the mobile screen widths but in desktop screen sizes, it has some issues.
  - The buttons should be aligned horizontally and not vertically in the popup like in the figma design.
  - Also the popup width is much more in the Figma design so kindly consider increasing the width of your popup in the desktop screens because in some desktop screen sizes, the elements in the popup gets overlapped with each other.
your design 
![t](https://user-images.githubusercontent.com/96683843/231586987-a715def4-db7f-4dfa-8319-23798ea772af.jpg)
![g](https://user-images.githubusercontent.com/96683843/231587039-d55773e1-5a60-4a8c-b73a-7bfc3f8bda50.jpg)


figma design
![qw](https://user-images.githubusercontent.com/96683843/231586386-99792f3b-7c66-4e5a-9961-1e72efeeee6a.jpg)

2023-04-13 16:04 UTC, NahnahAJ requested changes
## Project Status: CHANGES REQUIRED :recycle: 
Hi @shm04  and @asadmisrani  , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which haven't been addressed yet.
<img src="https://media2.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif"/>

 ## Highlights
- Popup works as expected :heavy_check_mark:
- No linter errors :heavy_check_mark:
- Professional Readme :heavy_check_mark:

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @NahnahAJ in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-13 16:04 UTC, NahnahAJ commented on index.html
>      <section class="works-section">
- [ ] Good job so far @shm04  and @asadmisrani. You did a good job with the popup functionality. However, As per the project requirements and as the previous reviewer mentioned, the projects section needs to be created dynamically. :+1: I have attached a screenshot below.
![image](https://user-images.githubusercontent.com/102699958/231513024-d2bd2106-4953-4ce7-9436-9ec29140495c.png)

- [ ] This means the projects section should be created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for the projects list should be removed, and instead, it should be added via JavaScript. :wink: 
- You can check an example of this student's project: https://github.com/olawale-o/portfolio-mobile-version/pull/15/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R95

2023-04-14 15:54 UTC, christianbiring1 requested changes
Hi @shm04 @asadmisrani , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
# STATUS: APPROVED :tada: 


 ## Highlights
- [ ] All linter checks are green :heavy_check_mark: 
- [ ] Descriptive PR `title` and `summary` :+1: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-14 15:54 UTC, christianbiring1 commented on script.js
> +const seeBtn = document.querySelectorAll('.see-btn');
- [ ] Great on rendering the project section dynamically as per project requirements, however, you may consider adjusting the size of your popup so that users may be able to open and close them easily for a better user experience as you may notice how the user cannot close the popup of the first, second projects and hardly the remaining ones.
### your design :point_down: 
![image](https://user-images.githubusercontent.com/97100091/232091760-3eae8ebd-f7c6-4951-9ff8-e35ef6917273.png)

2023-04-14 17:00 UTC, merged